### ISSUE TITLE
Cannot find string in BIOS extracted UEFI IFR data

### ISSUE THREAD

**Issue by Morzilla** [LongSoft/IFRExtractor-RS#20]
Hello! I cannot find the string "Overclocking Lock" in the extracted UEFI IFR data (with the command `ifrextractor.exe Section_PE32_image_Setup_Setup.sct verbose`) using the attached PE32 section sct (saved with UEFITool)

![image](https://github.com/LongSoft/IFRExtractor-RS/assets/3956663/a6ece76b-a446-4992-8d09-36d8045ef572)

this is the extracted PE32 Section image

[Section_PE32_image_Setup_Setup.zip](https://github.com/LongSoft/IFRExtractor-RS/files/12879033/Section_PE32_image_Setup_Setup.zip)

those are the results of the ifrextractor.exe extraction

[Section_PE32_image_Setup_Setup.bin.1.0.en-US.ifr.txt](https://github.com/LongSoft/IFRExtractor-RS/files/12879075/Section_PE32_image_Setup_Setup.bin.1.0.en-US.ifr.txt)
[Section_PE32_image_Setup_Setup.bin.0.0.en-US.ifr.txt](https://github.com/LongSoft/IFRExtractor-RS/files/12879076/Section_PE32_image_Setup_Setup.bin.0.0.en-US.ifr.txt)

Can you help me? What am I doing wrong? Thanks!

**Comment by NikolajSchlej** [comment]
You do nothing wrong, that string is a part of IFR string package, but not a part of IFR form package. It usually happens when a given VFR (the format that is compiled into IFR) source has conditional compilation (i.e. to remove BIOS Setup entries that aren't relevant for a release BIOS version), but the UNI (the file with all localized string) source remains shared for both. 

Basically, IFR extractor can't help you here, and you need to dig into disassembly to see of the code that applies the lock is still controlled by Setup variable or not.

**Comment by Morzilla** [comment]
Thank you very much... I'll try maybe with an older BIOS version!
